version: 2

builds:
  - main: .
    binary: relay
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "relay-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

dockers:
  - image_templates:
      - "ghcr.io/karmagate/karmagaterelay:{{ .Version }}"
      - "ghcr.io/karmagate/karmagaterelay:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
